### PR TITLE
Setup CircleCI and fix warning in main.go

### PR DESCRIPTION
**Pull request by soupdiver**
The image `soupdiver/fmb`probably should be moved to an entity managed by cloudradar.
I've also added the github key to CircleCI

### CODE REVIEW

**Comment by requilence** [comment]
What is inside `soupdiver/fmb`? It is a good practice to use docker's automatic build connected to the public github repo.

So all the images will be trusted by opensource/docker/github

**Comment by soupdiver** [comment]
> What is inside `soupdiver/fmb`?

See: https://github.com/cloudradar-monitoring/frontman/pull/2/files#diff-d92c0cc6cc3b84dda3c92547bcf56981
We should probably move it to some cloudradar controlled repo but to be able to proceed quickly I just put it under my personal account. It's just the image used to build the binaries.

>  It is a good practice to use docker's automatic build connected to the public github repo.
>
> So all the images will be trusted by opensource/docker/github

I don't fully understand what you mean. Yeah we can setup a hook that build and publishes the image when the Dockerfile is changed. Not sure how this hook relates to `So all the images will be trusted by opensource/docker/github`

**Comment by soupdiver** [comment]
> The problem is because you build it locally and push the binary image to docker hub as soupdiver/fmb users can't easily confirm that soupdiver/fmb is actually made from the actual codebase and doesn't contains some extra evil stuff 🙂

Ah yeah, that's why I not only referenced the image but also added the Dockerfile. If users don't trust external images they can build it by themselves.
To have a third party that produces the images just delegates the "issue". They can be hacked as well and add evil code... just as the Gentoo Github org was hacked a couple of days ago.
The only "safe" way will always be to build the images by yourself. You could then compare the hashes of the images to see if they match or not... but this is probably not the point of this discussion 😅 

I favour step 1 of the steps you mentioned, because that way we can reuse the build image.
With step 2 we have to recreate the build environment every time. Install things like git, goreleaser etc.
This costs time and resources, not that much I agree, but it adds up over time. Also the build environment is not guaranteed to be the same every time.

**Comment by requilence** [comment]
Totally agree. Even more I have just realised that because there is always be a way to push to github release directly there can't be a true "trusted" build

**Comment by soupdiver** [comment]
ok I will setup the repo for the Dockerfile.build, get a proper registry account and then adjust this PR

**Comment by requilence** [comment]
One more comment. You are probably need `rpmbuild` dep in order to build rpm package. I think it is not included in `rpm`

**Comment by soupdiver** [comment]
> One more comment. You are probably need rpmbuild dep in order to build rpm package. I think it is not included in rpm

[It is.](https://pkgs.alpinelinux.org/contents?file=rpmbuild&path=&name=rpm&branch=edge&repo=community&arch=x86)

**Comment by soupdiver** [comment]
moved to our own image repositroy

**Comment by soupdiver** [comment]
@requilence Also moved the Dockerfile into its own repo and setup hub.docker.com Automatic build

**Comment by requilence** [comment]
Cool! One more thing. Currently there is a `FRONTMAN_VERSION` env var encoded into the image.
We can unify this in order to work for frontman/cagent/csender and other possible future apps.

I'm using `***_VERSION` env var to inject ld flag to the compiler in the [.goreleaser.yml](https://github.com/cloudradar-monitoring/frontman/blob/master/.goreleaser.yml)
But according to the [goreleaser docs](https://goreleaser.com/environment/) they are already injecting lowercase `main.version` with the GIT tag. I will fix the goreleaser.yml and frontman/cagent/csender to make it works without this env var.

Lets merge for now and then you will fix the image

**Comment by requilence** [comment]
@soupdiver I have just pushed a new tag and release flow was failed because of missing `GITHUB_TOKEN` https://circleci.com/gh/cloudradar-monitoring/frontman/10

**Comment by soupdiver** [comment]
Fixed.
Not sure why the env var was suddenly missing 🤷‍♀️ 

Release is there: https://github.com/cloudradar-monitoring/frontman/releases/tag/0.6.10

**Comment by requilence** [comment]
Perfect. I have fixed frontman/cagent/csender repos. Now there is no need in `*_VERSION` vars. 

– You can safely change the image to omit it
– Add the circleci config to cagent&csender
– Not sure if it is critical but it will looks more clear if you rename the repo/image to something like *docker-go-builder*

**Comment by soupdiver** [comment]
> Not sure if it is critical but it will looks more clear if you rename the repo/image to something like docker-go-builder

yeah probably better to have one image for all apps and not app-specific ones

**Pull request merged**
